title: João Baiochi
logo: "/images/selfie_logo.png?raw=True"
description: >
    <i>Passionate about teaching, exploring data, finding insights and communicating through meaningful visualizations.</i>  
    <br><br> 
    <b>Skills</b>  
    <ul>
    <li>Python</li>
    <li>Machine Learning </li>
    <li>Data Visualization  </li>
    <li>PostgreSQL  </li>
    <li>R  </li>
    <li>WebScraping </li>
    </ul>
    <br><br>
    <a href="https://www.linkedin.com/in/joaobaiochi/">Linkedin Profile</a>

theme: jekyll-theme-minimal
