title: João Baiochi
logo: "/images/selfie_logo.png?raw=True"
description: >
    *Passionate about teaching, exploring data, finding insights and communicating through meaningful visualizations.*  
    <br><br> 
    **Skills**  
    - Python   
    - Machine Learning 
    - Data Visualization  
    - PostgreSQL  
    - R  
    - WebScraping  
    <br><br>
    [Linkedin Profile](https://www.linkedin.com/in/joaobaiochi/)

theme: jekyll-theme-minimal
